### PR TITLE
Make AOT and trimmed builds possible, with some associated cleanup.

### PR DESCRIPTION
**Pull request by henricj**
Note that this is on top of https://github.com/MediatedCommunications/Mime-Detective/pull/44

### CODE REVIEW

**Comment by TonyValenti** [comment]
I was just thinking about this PR yesterday. Glad it is coming along!  How close to "done" do you think you are?

**Comment by henricj** [comment]
> I was just thinking about this PR yesterday. Glad it is coming along! How close to "done" do you think you are?

There are a couple of concerns that have kept me from clicking "Ready for review."

1. There is now an additional assembly for `unsafe` code (required for memory mapping).  This may be more of an "executive decision" thing, in your court.
2. I have no idea how these changes impact the resulting NuGet packages, or if they even still work (I don't have any knowledge of problems; I simply haven't had a chance to look).
3. There are a lot of changes, and while the unit tests pass, more testing seems advisable.
4. I should read through the changes to see if there is anything I forgot...

OTOH, if you are okay with the above, I can click "Ready for review."

**Comment by henricj** [comment]
Err... and 5. That detection works at all (I'll push an update here soon).

**Comment by TonyValenti** [comment]
Excellent. Once you are pretty sure this is ready, I'll review and merge. My plan is to do a release in conjunction with .net 9.0 and this would fit perfectly for that timeline.

**Comment by henricj** [comment]
I'll have a look this weekend.

Going forward, and when I have some time, it would probably be worth exploring a change to how segments are represented.  Instead of copying data into new arrays, storing `Range` instances and passing in a `ReadOnlyMemory<>` or `ReadOnlySpan<>` would reduce GC pressure and likely be more performant.

One more thought: .NET 6 goes out of support when .NET 9 is released.

**Comment by TonyValenti** [comment]
.NEt 9.0 is out!
Do you think this is ready for merge?

**Comment by henricj** [comment]
> .NEt 9.0 is out! Do you think this is ready for merge?

I'd say it's in a state where I'd submit it for code review in my day job.  More eyes and more testing can always good, of course.

Go for it.

**Comment by henricj** [comment]
I've left some debug code in there.  I'll force push shortly.

```
-#if NET8_0_OR_GREATER && false
+#if NET8_0_OR_GREATER
```

**Comment by henricj** [comment]
This came up when building with the .NET 9 "dotnet" command:

```
$ dotnet build -c Release
Restore complete (0.6s)
  MimeDetective netstandard2.0 succeeded (1.0s) → MimeDetective\bin\Release\netstandard2.0\MimeDetective.dll
  MimeDetective net8.0 succeeded (1.3s) → MimeDetective\bin\Release\net8.0\MimeDetective.dll
  MimeDetective.MemoryMapping netstandard2.0 succeeded (0.2s) → MimeDetective.MemoryMapping\bin\Release\netstandard2.0\MimeDetective.MemoryMapping.dll
  MimeDetective.Definitions.Condensed netstandard2.0 succeeded (0.2s) → MimeDetective.Definitions.Condensed\bin\Release\netstandard2.0\MimeDetective.Definitions.Condensed.dll
  MimeDetective.Definitions.Exhaustive net8.0 succeeded (0.3s) → MimeDetective.Definitions.Exhaustive\bin\Release\net8.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective.MemoryMapping net8.0 succeeded (0.2s) → MimeDetective.MemoryMapping\bin\Release\net8.0\MimeDetective.MemoryMapping.dll
  MimeDetective.Definitions.Exhaustive netstandard2.0 succeeded (0.3s) → MimeDetective.Definitions.Exhaustive\bin\Release\netstandard2.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective.Definitions.Condensed net8.0 succeeded (0.7s) → MimeDetective.Definitions.Condensed\bin\Release\net8.0\MimeDetective.Definitions.Condensed.dll
  MimeDetective.Benchmark net48 succeeded with 1 warning(s) (0.4s) → MimeDetective.Benchmark\bin\Release\net48\MimeDetective.Benchmark.exe
    C:\Program Files\dotnet\sdk\9.0.100\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:
      Found conflicts between different versions of "System.Reflection.Metadata" that could not be resolved.
      There was a conflict between "System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
          "System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
          References which depend on "System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Users\henric\.nuget\packages\system.reflection.metadata\5.0.0\lib\net461\System.Reflection.Metadata.dll].
              C:\Users\henric\.nuget\packages\system.reflection.metadata\5.0.0\lib\net461\System.Reflection.Metadata.dll
                Project file item includes which caused reference "C:\Users\henric\.nuget\packages\system.reflection.metadata\5.0.0\lib\net461\System.Reflection.Metadata.dll".
                  C:\Users\henric\.nuget\packages\system.reflection.metadata\5.0.0\lib\net461\System.Reflection.Metadata.dll
          References which depend on or have been unified to "System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
              C:\Users\henric\.nuget\packages\microsoft.codeanalysis.common\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll
                Project file item includes which caused reference "C:\Users\henric\.nuget\packages\microsoft.codeanalysis.common\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll".
                  C:\Users\henric\.nuget\packages\microsoft.codeanalysis.common\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet\0.14.0\lib\netstandard2.0\BenchmarkDotNet.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet.diagnostics.windows\0.14.0\lib\netstandard2.0\BenchmarkDotNet.Diagnostics.Windows.dll
                  C:\Users\henric\.nuget\packages\microsoft.codeanalysis.csharp\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll
              C:\Users\henric\.nuget\packages\microsoft.codeanalysis.csharp\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll
                Project file item includes which caused reference "C:\Users\henric\.nuget\packages\microsoft.codeanalysis.csharp\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll".
                  C:\Users\henric\.nuget\packages\microsoft.codeanalysis.csharp\4.1.0\lib\netstandard2.0\Microsoft.CodeAnalysis.CSharp.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet\0.14.0\lib\netstandard2.0\BenchmarkDotNet.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet.diagnostics.windows\0.14.0\lib\netstandard2.0\BenchmarkDotNet.Diagnostics.Windows.dll
              C:\Users\henric\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.8\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll
                Project file item includes which caused reference "C:\Users\henric\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.8\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll".
                  C:\Users\henric\.nuget\packages\microsoft.diagnostics.tracing.traceevent\3.1.8\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet\0.14.0\lib\netstandard2.0\BenchmarkDotNet.dll
                  C:\Users\henric\.nuget\packages\benchmarkdotnet.diagnostics.windows\0.14.0\lib\netstandard2.0\BenchmarkDotNet.Diagnostics.Windows.dll
  MimeDetective(Tests) netstandard2.0 succeeded (0.5s) → MimeDetective(Tests)\bin\Release\netstandard2.0\MimeDetective(Tests).dll
  MimeDetective(Tests) net8.0 succeeded (0.7s) → MimeDetective(Tests)\bin\Release\net8.0\MimeDetective(Tests).dll
  MimeDetective.Benchmark net8.0 succeeded (0.5s) → MimeDetective.Benchmark\bin\Release\net8.0\MimeDetective.Benchmark.dll
  MimeDetective(Tests).Vb net462 succeeded (0.9s) → MimeDetective(Tests).Vb\bin\Release\net462\MimeDetective(Tests).Vb.dll
  MimeDetective.Definitions(Generator) succeeded (0.6s) → MimeDetective.Definitions(Generator)\bin\Release\net8.0\MimeDetective.Definitions(Generator).dll

Build succeeded with 1 warning(s) in 3.6s
```

**Comment by TonyValenti** [comment]
I'll merge both of your PRs as soon as you take them out of draft status.

**Comment by henricj** [comment]
I closed the other PR since it is all included in this one and hasn't been tested in a long time.  There is one other issue I'm aware of and that is that the Build.ps1 script fails if a `dotnet build -c Release` has never been run.  Otherwise, there should only be one warning left regarding the VB Test project:
```
  MimeDetective(Tests).Vb test net462 succeeded with 1 warning(s) (2.4s)
    C:\Program Files\dotnet\sdk\9.0.100\Microsoft.TestPlatform.targets(48,5): warning : No test is available in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective(Tests).Vb\bin\Debug\net462\MimeDetective(Tests).Vb.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by henricj** [comment]
This PR should be ready to go.  The VB test warning is simply stating truth and I'm not sure where the Build.ps1 script should be going, and if there should be changes, they should probably be through another PR (this one is big enough already).

**Pull request merged**
