### PR TITLE
Fix analyzer warnings

### PR DESCRIPTION
**Pull request by henricj**

### CODE REVIEW

**Comment by TonyValenti** [comment]
I'll merge this as soon as it is out of draft status.

**Comment by henricj** [comment]
I think the changes are sound, but while a lot was done by ReSharper and VS2022's automated fixes, some changes were done by hand.  The code under "src/MimeDetective/Definitions/" in particular required a lot of manual changes, so it would probably be wise for someone other than myself to scan through those changes carefully.  I was planning on trying to do another read through this weekend.

There are a number of remaining compiler warnings which suggests either merging as is, temporarily commenting out the analyzer settings, or fixing and/or disabling them (some may or may not be appropriate if they insist on changing the public API).  The current list of warnings is attached: [Mime-Detective.txt](https://github.com/user-attachments/files/17806927/Mime-Detective.txt)

For example,
```
C:\src\MIME\Mime-Detective\src\MimeDetective\Definitions\Default\Default.cs(6,29): warning CA1716: Rename type Default so that it no longer conflicts with the reserved language keyword 'Default'. Using a reserved keyword as the name of a type makes it harder for consumers in other languages to use the type. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1716) [C:\src\MIME\Mime-Detective\src\MimeDetective\MimeDetective.csproj::TargetFramework=netstandard2.0]
```
Would you want to rename it or squelch the CA1716 warning?

**Comment by TonyValenti** [comment]
> Would you want to rename it or squelch the CA1716 warning?

I'd say rename it.  And if you want to take care of some of the other warnings, (like 'Interfaces should start with I), go for it as well.

**Comment by TonyValenti** [comment]
When you are ready for me to merge, take this out of draft and let me know.

**Comment by henricj** [comment]
> When you are ready for me to merge, take this out of draft and let me know.

There are still 246 build warnings, and I still haven't had a chance to review the manual changes.

One question:  Visual Studio and/or ReSharper decided that the opening brace on the same line was preferred.  Yet, there is (was?) a lot of code where the opening brace is on a separate line.  Which do you prefer?  It is simple enough to set a flag and let the tools update the code.
With the opening brace on the same line:
```
if (flag) {
   Console.WriteLine("Hello, world!");
}
```
or on a separate line:
```
if (flag)
{
   Console.WriteLine("Hello, world!");
}
```
?

**Comment by TonyValenti** [comment]
I prefer the first where the curly is NOT on its own line.

**Comment by henricj** [comment]
The manual changes have been reviewed, `.editorconfig` has been applied to everything, and all but four warnings have been
fixed.  The remaining warnings are for things named `Default` and `Date`.  Any ideas as to what might be better names?

The build now looks like this:

```
$ ./Build.ps1
build: Build started
build: Cleaning .\artifacts
Restore complete (3.0s)

Build succeeded in 3.3s
Restore complete (2.1s)
  MimeDetective netstandard2.0 succeeded with 2 warning(s) (3.9s) → MimeDetective\bin\Release\netstandard2.0\MimeDetective.dll
    C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\Definitions\Default\Default.cs(6,29): warning CA1716: Rename type Default so that it no longer conflicts with the reserved language keyword 'Default'. Using a reserved keyword as the name of a type makes it harder for consumers in other languages to use the type. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1716)
    C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\Storage\Xml\v2\Date.cs(6,14): warning CA1716: Rename type Date so that it no longer conflicts with the reserved language keyword 'Date'. Using a reserved keyword as the name of a type makes it harder for consumers in other languages to use the type. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1716)
  MimeDetective net8.0 succeeded with 2 warning(s) (3.2s) → MimeDetective\bin\Release\net8.0\MimeDetective.dll
    C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\Definitions\Default\Default.cs(6,29): warning CA1716: Rename type Default so that it no longer conflicts with the reserved language keyword 'Default'. Using a reserved keyword as the name of a type makes it harder for consumers in other languages to use the type. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1716)
    C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\Storage\Xml\v2\Date.cs(6,14): warning CA1716: Rename type Date so that it no longer conflicts with the reserved language keyword 'Date'. Using a reserved keyword as the name of a type makes it harder for consumers in other languages to use the type. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1716)
  MimeDetective.MemoryMapping netstandard2.0 succeeded (0.7s) → MimeDetective.MemoryMapping\bin\Release\netstandard2.0\MimeDetective.MemoryMapping.dll
  MimeDetective.Definitions.Exhaustive netstandard2.0 succeeded (0.8s) → MimeDetective.Definitions.Exhaustive\bin\Release\netstandard2.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective.Definitions.Condensed netstandard2.0 succeeded (0.8s) → MimeDetective.Definitions.Condensed\bin\Release\netstandard2.0\MimeDetective.Definitions.Condensed.dll
  MimeDetective.Definitions.Condensed net8.0 succeeded (1.1s) → MimeDetective.Definitions.Condensed\bin\Release\net8.0\MimeDetective.Definitions.Condensed.dll
  MimeDetective.MemoryMapping net8.0 succeeded (1.1s) → MimeDetective.MemoryMapping\bin\Release\net8.0\MimeDetective.MemoryMapping.dll
  MimeDetective.Definitions.Exhaustive net8.0 succeeded (0.7s) → MimeDetective.Definitions.Exhaustive\bin\Release\net8.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective(Tests) net48 succeeded (1.4s) → MimeDetective(Tests)\bin\Release\net48\MimeDetective(Tests).dll
  MimeDetective.Benchmark net48 succeeded (1.6s) → MimeDetective.Benchmark\bin\Release\net48\MimeDetective.Benchmark.exe
  MimeDetective(Tests) net8.0 succeeded (2.4s) → MimeDetective(Tests)\bin\Release\net8.0\MimeDetective(Tests).dll
  MimeDetective.Console.AOT net8.0 succeeded (1.3s) → Samples\MimeDetective.Console.AOT\bin\Release\net8.0\MimeDetective.Console.AOT.dll
  MimeDetective.Benchmark net8.0 succeeded (1.4s) → MimeDetective.Benchmark\bin\Release\net8.0\MimeDetective.Benchmark.dll
  MimeDetective.MinimalApi.AOT net9.0 succeeded (5.2s) → Samples\MimeDetective.MinimalApi.AOT\bin\Release\net9.0\MimeDetective.MinimalApi.AOT.dll
  MimeDetective(Tests).Vb net462 succeeded (3.9s) → MimeDetective(Tests).Vb\bin\Release\net462\MimeDetective(Tests).Vb.dll
  MimeDetective.Definitions(Generator) net8.0 succeeded (1.8s) → MimeDetective.Definitions(Generator)\bin\Release\net8.0\MimeDetective.Definitions(Generator).dll

Build succeeded with 4 warning(s) in 14.0s
build: Package version suffix is
build: Build version suffix is
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective

Build succeeded in 1.0s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Benchmark

Build succeeded in 0.2s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Definitions.Condensed

Build succeeded in 0.9s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Definitions.Exhaustive

Build succeeded in 1.3s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Definitions(Generator)

Build succeeded in 0.2s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.MemoryMapping

Build succeeded in 0.9s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective(Tests)

Build succeeded in 0.2s
build: Packaging project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective(Tests).Vb

Build succeeded in 0.2s
build: Testing project in C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective(Tests)
Restore complete (0.5s)
  MimeDetective netstandard2.0 succeeded (0.1s) → C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\bin\Release\netstandard2.0\MimeDetective.dll
  MimeDetective net8.0 succeeded (0.1s) → C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective\bin\Release\net8.0\MimeDetective.dll
  MimeDetective.Definitions.Exhaustive netstandard2.0 succeeded (0.1s) → C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Definitions.Exhaustive\bin\Release\netstandard2.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective.Definitions.Exhaustive net8.0 succeeded (0.1s) → C:\src\rootapp\MIME\Mime-Detective\src\MimeDetective.Definitions.Exhaustive\bin\Release\net8.0\MimeDetective.Definitions.Exhaustive.dll
  MimeDetective(Tests) net48 succeeded (0.1s) → bin\Release\net48\MimeDetective(Tests).dll
  MimeDetective(Tests) net8.0 succeeded (0.2s) → bin\Release\net8.0\MimeDetective(Tests).dll
  MimeDetective(Tests) test net8.0 succeeded (39.5s)
  MimeDetective(Tests) test net48 succeeded (54.1s)

Test summary: total: 174, failed: 0, succeeded: 170, skipped: 4, duration: 54.1s
Build succeeded in 55.6s
```

**Comment by henricj** [comment]
Those four warnings are now the only reason I haven't clicked the "Ready for review" button.

**Comment by TonyValenti** [comment]
I'm not worried about that. Once I merge I'll rename those to something that doesn't generate earnings.

**Comment by henricj** [comment]
After fixing those last few warnings, tell the compiler to [treat all warnings as errors](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors) by adding

```
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```

to `Directory.Build.props`.

**Pull request merged**
